# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  (1..5).each do |i|
    config.vm.define "n#{i}" do |node|
      node.vm.box = "bento/ubuntu-24.04"

      node.vm.provider "virtualbox" do |vb|
        vb.memory = "8240"
        vb.cpus = 4
      end

      node.vm.network "private_network", ip: "192.168.56.10#{i}"

      node.vm.hostname = "n#{i}"

      # install necessary packages
      node.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update

        # ifconfig
        sudo apt-get install -y net-tools
      SHELL

      # default user: vagrant, password: vagrant
      # ssh from host machine: ssh vagrant@192.168.56.10#{i}
      node.vm.provision "shell", inline: <<-SHELL
        # enable password authentication
        sudo sed -i 's/^#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
        sudo sed -i 's/^PasswordAuthentication no/#PasswordAuthentication no/' /etc/ssh/sshd_config

        # NOTE: use "ssh" instead of "sshd" for this box
        sudo systemctl restart ssh
      SHELL
    end
  end
end
