# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "8240"
    vb.cpus = 4
  end

  config.vm.hostname = "n1"
  config.vm.provision "shell", inline: <<-SHELL
    echo "root:vagrant" | sudo chpasswd
    sudo sed -i 's/^#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
    sudo sed -i 's/^PasswordAuthentication no/#PasswordAuthentication no/' /etc/ssh/sshd_config
    sudo systemctl restart sshd
  SHELL
end
